//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SchoolProject.CMS_SchoolEdModel", "CMS_SiteMenu", "CMS_Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS_SchoolProjectEntity.Entity.CMS_Menu), "CMS_Site", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CMS_SchoolProjectEntity.Entity.CMS_Site))]

#endregion

namespace CMS_SchoolProjectEntity.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CMS_SchoolProjectEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CMS_SchoolProjectEntities object using the connection string found in the 'CMS_SchoolProjectEntities' section of the application configuration file.
        /// </summary>
        public CMS_SchoolProjectEntities() : base("name=CMS_SchoolProjectEntities", "CMS_SchoolProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMS_SchoolProjectEntities object.
        /// </summary>
        public CMS_SchoolProjectEntities(string connectionString) : base(connectionString, "CMS_SchoolProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMS_SchoolProjectEntities object.
        /// </summary>
        public CMS_SchoolProjectEntities(EntityConnection connection) : base(connection, "CMS_SchoolProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CMS_Menu> CMS_Menu
        {
            get
            {
                if ((_CMS_Menu == null))
                {
                    _CMS_Menu = base.CreateObjectSet<CMS_Menu>("CMS_Menu");
                }
                return _CMS_Menu;
            }
        }
        private ObjectSet<CMS_Menu> _CMS_Menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CMS_Site> CMS_Site
        {
            get
            {
                if ((_CMS_Site == null))
                {
                    _CMS_Site = base.CreateObjectSet<CMS_Site>("CMS_Site");
                }
                return _CMS_Site;
            }
        }
        private ObjectSet<CMS_Site> _CMS_Site;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CMS_Menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCMS_Menu(CMS_Menu cMS_Menu)
        {
            base.AddObject("CMS_Menu", cMS_Menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CMS_Site EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCMS_Site(CMS_Site cMS_Site)
        {
            base.AddObject("CMS_Site", cMS_Site);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolProject.CMS_SchoolEdModel", Name="CMS_Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CMS_Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CMS_Menu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="uRL">Initial value of the URL property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static CMS_Menu CreateCMS_Menu(global::System.Guid id, global::System.String name, global::System.String uRL, global::System.String description, global::System.DateTime dateCreated)
        {
            CMS_Menu cMS_Menu = new CMS_Menu();
            cMS_Menu.Id = id;
            cMS_Menu.Name = name;
            cMS_Menu.URL = uRL;
            cMS_Menu.Description = description;
            cMS_Menu.DateCreated = dateCreated;
            return cMS_Menu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, false, "URL");
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value, "DateCreated");
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserCreated
        {
            get
            {
                return _UserCreated;
            }
            set
            {
                OnUserCreatedChanging(value);
                ReportPropertyChanging("UserCreated");
                _UserCreated = StructuralObject.SetValidValue(value, "UserCreated");
                ReportPropertyChanged("UserCreated");
                OnUserCreatedChanged();
            }
        }
        private Nullable<global::System.Int32> _UserCreated;
        partial void OnUserCreatedChanging(Nullable<global::System.Int32> value);
        partial void OnUserCreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolProject.CMS_SchoolEdModel", "CMS_SiteMenu", "CMS_Site")]
        public EntityCollection<CMS_Site> CMS_Site
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CMS_Site>("SchoolProject.CMS_SchoolEdModel.CMS_SiteMenu", "CMS_Site");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CMS_Site>("SchoolProject.CMS_SchoolEdModel.CMS_SiteMenu", "CMS_Site", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolProject.CMS_SchoolEdModel", Name="CMS_Site")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CMS_Site : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CMS_Site object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static CMS_Site CreateCMS_Site(global::System.Guid id, global::System.String name, global::System.String description, global::System.DateTime dateCreated)
        {
            CMS_Site cMS_Site = new CMS_Site();
            cMS_Site.Id = id;
            cMS_Site.Name = name;
            cMS_Site.Description = description;
            cMS_Site.DateCreated = dateCreated;
            return cMS_Site;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value, "DateCreated");
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserCreated
        {
            get
            {
                return _UserCreated;
            }
            set
            {
                OnUserCreatedChanging(value);
                ReportPropertyChanging("UserCreated");
                _UserCreated = StructuralObject.SetValidValue(value, "UserCreated");
                ReportPropertyChanged("UserCreated");
                OnUserCreatedChanged();
            }
        }
        private Nullable<global::System.Int32> _UserCreated;
        partial void OnUserCreatedChanging(Nullable<global::System.Int32> value);
        partial void OnUserCreatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolProject.CMS_SchoolEdModel", "CMS_SiteMenu", "CMS_Menu")]
        public EntityCollection<CMS_Menu> CMS_Menu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CMS_Menu>("SchoolProject.CMS_SchoolEdModel.CMS_SiteMenu", "CMS_Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CMS_Menu>("SchoolProject.CMS_SchoolEdModel.CMS_SiteMenu", "CMS_Menu", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
