//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMS_Content()
        {
            this.CMS_Placeholder = new HashSet<CMS_Placeholder>();
        }
    
        public System.Guid ContentId { get; set; }
        public string ContentHeader { get; set; }
        public bool IsDeprecated { get; set; }
        public System.Guid MenuId { get; set; }
    
        public virtual CMS_Site CMS_Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMS_Placeholder> CMS_Placeholder { get; set; }
    }
}
