//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMS_SchoolEdEntities1 : DbContext
    {
        public CMS_SchoolEdEntities1()
            : base("name=CMS_SchoolEdEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMS_Content> CMS_Content { get; set; }
        public virtual DbSet<CMS_Menu> CMS_Menu { get; set; }
        public virtual DbSet<CMS_Placeholder> CMS_Placeholder { get; set; }
        public virtual DbSet<CMS_Settings> CMS_Settings { get; set; }
        public virtual DbSet<CMS_Site> CMS_Site { get; set; }
    }
}
